---
output: 
  html_document:
    anchor_sections: TRUE
css: styles.css
runtime: shiny
---

# Seagrass transect training {.tabset}
  
```{r setup, message = F, warning = F, results = 'hide', echo = FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = F, message = F, echo = F, fig.path = 'figs/', fig.path = 'figures/')

library(tidyverse)
library(tbeptools)
library(shiny)
library(reactable)
library(mapview)

# for leaflet map
data(trnlns)
data(trnpts)

trnpts <- trnpts %>% 
  unite('lonlat', LONG_DD, LAT_DD, sep = ',') %>% 
  unite('lab', TRAN_ID, lonlat, sep = ': ', remove = F) %>% 
  mutate(lab = paste0('Transect: ', lab))

trnlns <- trnlns %>% 
  filter(as.character(Site) %in% trnpts$TRAN_ID)

# get data and format
dat <- read_transect(training = TRUE)

# get choices for selection
sppopt <- unique(dat$Savspecies)

downloadButtonRmd <- function (outputId, label, class = NULL, ...)  {
  tags$a(id = outputId, class = paste("btn btn-default shiny-download-link", 
                                      class), href = "", target = "_blank", download = NA, 
         icon("download"), label, ...)
}

# metric summary
datsum <- dat %>% 
  dplyr::mutate(
    grp = paste0(MonitoringAgency, ' (', Crew, ')')
  ) %>% 
  group_by(yr, Site, Savspecies, var) %>% 
  summarise(
    cv = 100 * sd(aveval, na.rm = T) / mean(aveval, na.rm = T), 
    .groups = 'drop'
    ) %>% 
  na.omit()

# # style file
# styles <- readLines('https://raw.githubusercontent.com/tbep-tech/css-styling/master/styles.css')
# writeLines(styles, 'styles.css')
```


```{r downloadhandlers}
# wq data
output$dlfigs <- downloadHandler(
  filename = function(){'allfigures.pdf'},
  content = function(file){

    # input
    yrssel <- input$yrssel
    
    todl <- dat %>% 
      filter(yr %in% yrssel) %>% 
      select(Savspecies, var, Site) %>% 
      unique %>% 
      arrange(Savspecies, var, Site)

    pdf(file, width = input$width, height = input$height)
    
    for(i in 1:nrow(todl)){
      
      site <- todl[[i, 'Site']]
      species <- todl[[i, 'Savspecies']]
      varplo <- todl[[i, 'var']]
      
      p <- show_compplot(dat, yrssel, site, species, varplo)
      
      print(p)
      
    }
      
    dev.off()
    
  }
)
```

```{r reactives}
plodat <- reactive({
  
  # inputs
  yrssel <- input$yrssel
  sppsel <- input$sppsel
  sitsel <- input$sitsel
  varsel <- input$varsel

  out <- show_compplot(dat, yrssel, sitsel, sppsel, varsel, base_size = 18, xtxt = 13)
  
  validate(
    need(nrow(out$data) > 0, 'No data to plot')
  )
  
  return(out)
  
})

sumplodat <- reactive({
  
  # input
  yrssel <- input$yrssel
  
  toplo <- datsum %>% 
    filter(yr == yrssel)
  
  out <- ggplot(toplo, aes(x = Site, y = var, fill = cv)) +
    facet_wrap(~Savspecies, ncol  = 2) + 
    scale_x_discrete(expand = c(0, 0)) + 
    scale_y_discrete(expand = c(0, 0)) +
    geom_tile(colour = 'black') + 
    scale_fill_gradientn('CV %', colours = c('lightgreen', 'tomato1')) + 
    theme_bw(base_size = 16) + 
    theme(
      strip.background = element_blank(), 
      # panel.background = element_blank(), 
      panel.grid = element_blank(), 
      axis.title.y = element_blank()
    ) + 
    labs(
      subtitle = "Metric variation among sites and species", 
      caption = 'CV is st. dev. / mean that captures differences among crews'
    )

  return(out)
  
})

crewtab <- reactive({
  
  # input
  yrssel <- input$yrssel
  
  totab <- dat %>% 
    filter(yr %in% yrssel) %>% 
    select(`Montoring Agency` = MonitoringAgency, Crew) %>% 
    unique

  out <- reactable(totab, 
    groupBy = 'Montoring Agency',
    defaultColDef = colDef(
      footerStyle = list(fontWeight = "bold"),
      resizable = TRUE
      ),
    columns = list(
      Crew = colDef(aggregated = JS("
        function(cellInfo) {
          // Get comma-separated list of unique values in visible rows
          var values = cellInfo.subRows.map(function(row) { return row.Crew })
          var unique = values.reduce(function(obj, v) { obj[v] = true; return obj }, {})
          return Object.keys(unique).join(', ')
        }
      ")
      )
    ),
    filterable = T, 
    bordered = T
  )
  
  return(out)
  
})
```

```{r}
column(12, 
  column(4, selectInput('yrssel', 'Select year:', choices = sort(unique(dat$yr))))
)
```

## Plot results {.tabset .tabset-pills}

```{r}
column(12, 
  column(4, selectInput('sppsel', 'Select species:', choices = sppopt)),
  column(4, renderUI({
    
    # input
    yrssel <- input$yrssel
    
    sitopt <- dat %>% 
      filter(yr %in% yrssel) %>% 
      pull(Site) %>% 
      unique() %>% 
      sort()
    
    selectInput('sitsel', 'Select site:', choices = sitopt)
    
    })
  ),
  column(4, selectInput('varsel', 'Select variable:', choices =  unique(dat$var)))
)
```

### Individual 

```{r, fig.align = 'center'}
output$plo <- renderPlot(plodat(), height = 600, width = 850)
plotOutput('plo')
```

### Summary

```{r, fig.align = 'center'}
output$sumplodat <- renderPlot(sumplodat(), height = 600, width = 850)
plotOutput('sumplodat')
```

## Crew inventory

```{r}
output$crewtab <- renderReactable(crewtab())
reactableOutput('crewtab')
```

## Transect locations

```{r, out.width = '100%'}
cols <- c("#E16A86", "#CB7F2F", "#9F9400", "#50A315", "#00AC79", "#00AAB7", "#009ADE", "#A87BE4", "#DA65C3")

mapview(trnpts, zcol = 'MonAgency', lwd = 0, legend = F, homebutton = F, col.regions = cols) + 
  mapview(trnlns, zcol = 'MonAgency', homebutton = F, layer.name = 'Monitoring Agency', lwd = 4, color = cols)
```

## Download 

Download all figures for `r renderText(input$yrssel)`.

```{r}
column(6,  
  HTML('<br></br>'),
  downloadButtonRmd('dlfigs', 'Download all figures'),
  HTML('<br></br>'),
  numericInput('height', 'Plot heights (in)', value = 7, min = 0, step = 1),
  numericInput('width', 'Plot widths (in)', value = 8, min = 0, step = 1)
)
```

